
parameters:
- name: JobName
  type: string
  default: DisableRepoJob
- name: HostedAgentPool
  displayName: Hosted agent pool to run on
  type: string
  default: ubuntu-latest
- name: DependsOn 
  type: string
  default: ''
- name: Repo
  type: string
- name: AdoOrganizationUrl
  type: string
  default: '$(System.CollectionUri)'
- name: AdoTeamProject
  type: string
  default: '$(System.TeamProject)'
- name: AdoAccessToken
  type: string
  default: '$(System.AccessToken)'

jobs:
- job: ${{ parameters.JobName }}
  displayName: Get All Pipeline Info
  dependsOn: ${{ parameters.DependsOn }}
  pool: 
    vmImage: ${{ parameters.HostedAgentPool }}

  steps: 
  - checkout: self
    clean: true

  - pwsh: | 
      dir ENV:
    displayName: diags
