
parameters:
- name: JobName
  type: string
  default: SetBranchStateJob
- name: HostedAgentPool
  displayName: Hosted agent pool to run on
  type: string
  default: ubuntu-latest
- name: DependsOn 
  type: object
  default: ''
- name: Repo
  type: string
- name: State
  type: string
  values: 
  - locked
  - unlocked
- name: Branch
  type: string
  default: ''
- name: WhatIf
  displayName: What If
  type: boolean
  default: true
- name: AdoOrganizationUrl
  type: string
  default: '$(System.CollectionUri)'
- name: AdoTeamProject
  type: string
  default: '$(System.TeamProject)'
- name: AdoAccessToken
  type: string
  default: '$(System.AccessToken)'
- name: Condition
  type: string
  default: succeeded()

jobs:
- job: ${{ parameters.JobName }}
  displayName: Setting branches in ${{ parameters.Repo }} to ${{ parameters.State }}
  dependsOn: ${{ parameters.DependsOn }}
  condition: ${{ parameters.Condition }}
  pool: 
    vmImage: ${{ parameters.HostedAgentPool }}

  variables:
    - ${{ if eq( parameters.WhatIf, true )}}:
      - name: WhatIfForPwsh
        value: '$true'
    - ${{ else }}:
      - name: WhatIfForPwsh
        value: '$false'

  steps: 
  - checkout: ${{ parameters.Repo }}
    path: s/ado-source
    clean: true

  - checkout: self
    clean: true

  - task: PowerShell@2
    displayName: 'Set Branches in ${{ parameters.Repo }} to ${{ parameters.State }}'
    inputs:
      targetType: filePath
      filePath: $(Build.Repository.LocalPath)/$(Build.Repository.Name)/pwsh/set-repobranchstate.ps1
      pwsh: true
      arguments: >
        -OrganizationUri '${{ parameters.AdoOrganizationUrl }}'
        -Project '${{ parameters.AdoTeamProject }}'
        -Repo '${{ parameters.Repo }}'
        -State ${{ parameters.State }}
        -Branch '${{ parameters.Branch }}'
        -WhatIf:${{ variables.WhatIfForPwsh }}
    env:
      AZURE_DEVOPS_EXT_PAT: ${{ parameters.AdoAccessToken }}
