trigger: none
pr: none
parameters:
- name: MigrationData
  displayName: Migration Data
  type: object
  default:
  - repo:
      SourceAdoRepo: epr-data
      TargetGitHubRepo: epr-data
      Action: synchronize
  - repo:
      SourceAdoRepo: epr-migration-automation
      TargetGitHubRepo: epr-migration-automation
      Action: synchronize
  - repo:
      SourceAdoRepo: epr-migration-test1
      TargetGitHubRepo: epr-migration-test1
      Action: synchronize
  - repo:
      SourceAdoRepo: epr-migration-test2
      TargetGitHubRepo: epr-migration-test2
      Action: synchronize
  - repo:
      SourceAdoRepo: epr-webapps-code-deploy-pipelines
      TargetGitHubRepo: epr-webapps-code-deploy-pipelines
      Action: synchronize
  - repo:
      SourceAdoRepo: epr-webapps-code-deploy-templates
      TargetGitHubRepo: epr-webapps-code-deploy-templates
      Action: synchronize
- name: GitLeaksFailureAsWarning
  displayName: Treat Gitleaks failure as partial success
  type: boolean
  default: false
- name: GitHubRepoSettings
  type: object
  default:
  - name: allow-update-branch
    value: true
  - name: default-branch
    value: main
  - name: delete-branch-on-merge
    value: true
  - name: enable-auto-merge
    value: true
  - name: enable-discussions
    value: false
  - name: enable-issues
    value: true
  - name: enable-merge-commit
    value: false
  - name: enable-projects
    value: true
  - name: enable-rebase-merge
    value: false
  - name: enable-squash-merge
    value: true
  - name: enable-wiki
    value: true
variables:
- group: DefraGitHub
- name: GitHubPipelineServiceConnection
  value: Defra
- name: WindowsHostedAgentPool
  value: windows-latest
- name: UbuntuHostedAgentPool
  value: ubuntu-latest
- name: AllPipelinesJsonArtifactName
  value: AllPipelinesJson
- name: RenamePrefix
  value: ZZZ-Archive-
resources:
  repositories:
  - repository: epr-data
    name: RWD-CPR-EPR4P-ADO/epr-data
    type: git
  - repository: github-epr-data
    name: defra/epr-data
    type: github
    endpoint: GitHubMigration
  - repository: epr-migration-automation
    name: RWD-CPR-EPR4P-ADO/epr-migration-automation
    type: git
  - repository: github-epr-migration-automation
    name: defra/epr-migration-automation
    type: github
    endpoint: GitHubMigration
  - repository: epr-migration-test1
    name: RWD-CPR-EPR4P-ADO/epr-migration-test1
    type: git
  - repository: github-epr-migration-test1
    name: defra/epr-migration-test1
    type: github
    endpoint: GitHubMigration
  - repository: epr-migration-test2
    name: RWD-CPR-EPR4P-ADO/epr-migration-test2
    type: git
  - repository: github-epr-migration-test2
    name: defra/epr-migration-test2
    type: github
    endpoint: GitHubMigration
  - repository: epr-webapps-code-deploy-pipelines
    name: RWD-CPR-EPR4P-ADO/epr-webapps-code-deploy-pipelines
    type: git
  - repository: github-epr-webapps-code-deploy-pipelines
    name: defra/epr-webapps-code-deploy-pipelines
    type: github
    endpoint: GitHubMigration
  - repository: epr-webapps-code-deploy-templates
    name: RWD-CPR-EPR4P-ADO/epr-webapps-code-deploy-templates
    type: git
  - repository: github-epr-webapps-code-deploy-templates
    name: defra/epr-webapps-code-deploy-templates
    type: github
    endpoint: GitHubMigration
extends:
  template: templates/pipeline-migration.yaml
  parameters:
    AdoAccessToken: $(System.AccessToken)
    AdoOrganizationUrl: $(System.CollectionUri)
    AdoTeamProject: $(System.TeamProject)
    AllPipelinesJsonArtifactName: ${{ variables.AllPipelinesJsonArtifactName }}
    GitHubAccessToken: $(GitHubAccessToken)
    GitHubOrganizationName: $(GitHubOrganizationName)
    GitHubPipelineServiceConnection: $(GitHubPipelineServiceConnection)
    GitHubRepoSettings: ${{ parameters.GitHubRepoSettings }}
    GitHubServiceConnection: $(GitHubServiceConnection)
    GitLeaksFailureAsWarning: ${{ parameters.GitLeaksFailureAsWarning }}
    MigrationData: ${{ parameters.MigrationData }}
    RenamePrefix: ${{ variables.RenamePrefix }}
    UbuntuHostedAgentPool: ${{ variables.UbuntuHostedAgentPool }}
    WindowsHostedAgentPool: ${{ variables.WindowsHostedAgentPool }}

