trigger: none

parameters:
- name: Repos
  displayName: Repos to sync
  type: object
  default: 
    - epr-migration-test1
    - epr-migration-test2
    - epr-migration-automation

- name: Mode
  displayName: Operating mode
  type: string
  default: Synchronize
  values: 
  - Synchronize
  - Migrate

- name: WhatIf
  displayName: WhatIf
  type: boolean
  default: true

variables:
- name: GitHubOrganizationName
  value: defra
- name: GitHubServiceConnection
  value: defra

resources: 
  repositories:
  # epr-migration-test1
  - repository: ado-epr-migration-test1
    name: RWD-CPR-EPR4P-ADO/epr-migration-test1
    type: git
  - repository: github-epr-migration-test1
    name: defra/epr-migration-test1
    type: github
    endpoint: defra

  # epr-migration-test2
  - repository: ado-epr-migration-test2
    name: RWD-CPR-EPR4P-ADO/epr-migration-test2
    type: git
  - repository: github-epr-migration-test2
    name: defra/epr-migration-test2
    type: github
    endpoint: defra

  # epr-migration-automation
  - repository: ado-epr-migration-automation
    name: RWD-CPR-EPR4P-ADO/epr-migration-automation
    type: git
  - repository: github-epr-migration-automation
    name: defra/epr-migration-automation
    type: github
    endpoint: defra

extends: 
  template: templates/pipeline-migration.yaml
  parameters: 
    Repos: ${{ parameters.Repos }}
    Mode: ${{ parameters.Mode }}
    GitHubOrganizationName: ${{ variables.GitHubOrganizationName }}
    GitHubServiceConnection: ${{ variables.GitHubServiceConnection }}
    AdoOrganizationUrl: $(System.CollectionUri)
    AdoTeamProject: $(System.TeamProject)
    AdoAccessToken: $(System.AccessToken)
    WhatIf: ${{ parameters.WhatIf }}

