trigger: none
pr: none
parameters:
- name: MigrationData
  displayName: Migration Data
  type: object
  default:
  - repo:
      SourceAdoRepo: epr-app-config-settings
      TargetGitHubRepo: epr-app-config-settings
      Action: synchronize
  - repo:
      SourceAdoRepo: backend-account-microservice
      TargetGitHubRepo: epr-backend-account-microservice
      Action: synchronize
  - repo:
      SourceAdoRepo: epr_common
      TargetGitHubRepo: epr-common
      Action: synchronize
  - repo:
      SourceAdoRepo: epr-common-data-api
      TargetGitHubRepo: epr-common-data-api
      Action: synchronize
  - repo:
      SourceAdoRepo: epr-data
      TargetGitHubRepo: epr-data
      Action: synchronize
  - repo:
      SourceAdoRepo: epr-event-dispatcher-function-app
      TargetGitHubRepo: epr-event-dispatcher-function-app
      Action: synchronize
  - repo:
      SourceAdoRepo: facade-account-microservice
      TargetGitHubRepo: epr-facade-account-microservice
      Action: synchronize
  - repo:
      SourceAdoRepo: frontend-accountcreation-microservice
      TargetGitHubRepo: epr-frontend-accountcreation-microservice
      Action: synchronize
  - repo:
      SourceAdoRepo: frontend-accountmanagement-microservice
      TargetGitHubRepo: epr-frontend-accountmanagement-microservice
      Action: synchronize
  - repo:
      SourceAdoRepo: epr-logging-api
      TargetGitHubRepo: epr-logging-api
      Action: synchronize
  - repo:
      SourceAdoRepo: epr-migration-automation
      TargetGitHubRepo: epr-migration-automation
      Action: synchronize
  - repo:
      SourceAdoRepo: epr-migration-test1
      TargetGitHubRepo: epr-migration-test1
      Action: synchronize
  - repo:
      SourceAdoRepo: epr-migration-test2
      TargetGitHubRepo: epr-migration-test2
      Action: synchronize
  - repo:
      SourceAdoRepo: epr-obligationchecker-frontend
      TargetGitHubRepo: epr-obligationchecker-frontend
      Action: synchronize
  - repo:
      SourceAdoRepo: epr_packaging_frontend
      TargetGitHubRepo: epr-packaging-frontend
      Action: synchronize
  - repo:
      SourceAdoRepo: epr_pom_api_submission_status
      TargetGitHubRepo: epr-pom-api-submission-status
      Action: synchronize
  - repo:
      SourceAdoRepo: epr_pom_api_web
      TargetGitHubRepo: epr-pom-api-web
      Action: synchronize
  - repo:
      SourceAdoRepo: epr_pom_func_producer_validation
      TargetGitHubRepo: epr-pom-func-producer-validation
      Action: synchronize
  - repo:
      SourceAdoRepo: epr_pom_func_submission_check_splitter
      TargetGitHubRepo: epr-pom-func-submission-check-splitter
      Action: synchronize
  - repo:
      SourceAdoRepo: epr-registration-validation-function-app
      TargetGitHubRepo: epr-registration-validation-function-app
      Action: synchronize
  - repo:
      SourceAdoRepo: epr-regulator-enrolment-frontend
      TargetGitHubRepo: epr-regulator-enrolment-frontend
      Action: synchronize
  - repo:
      SourceAdoRepo: epr_regulator_service
      TargetGitHubRepo: epr-regulator-service
      Action: synchronize
  - repo:
      SourceAdoRepo: epr_regulator_service_facade
      TargetGitHubRepo: epr-regulator-service-facade
      Action: synchronize
  - repo:
      SourceAdoRepo: epr-rpd-performance-tests
      TargetGitHubRepo: epr-rpd-performance-tests
      Action: synchronize
  - repo:
      SourceAdoRepo: epr_ui_wdio
      TargetGitHubRepo: epr-ui-wdio
      Action: synchronize
  - repo:
      SourceAdoRepo: epr-webapps-code-deploy-pipelines
      TargetGitHubRepo: epr-webapps-code-deploy-pipelines
      Action: synchronize
  - repo:
      SourceAdoRepo: epr-webapps-code-deploy-templates
      TargetGitHubRepo: epr-webapps-code-deploy-templates
      Action: synchronize
- name: GitLeaksFailureAsWarning
  displayName: Treat Gitleaks failure as partial success
  type: boolean
  default: false
- name: GitHubRepoSettings
  type: object
  default:
  - name: allow-update-branch
    value: true
  - name: default-branch
    value: main
  - name: delete-branch-on-merge
    value: true
  - name: enable-auto-merge
    value: true
  - name: enable-discussions
    value: false
  - name: enable-issues
    value: true
  - name: enable-merge-commit
    value: false
  - name: enable-projects
    value: true
  - name: enable-rebase-merge
    value: false
  - name: enable-squash-merge
    value: true
  - name: enable-wiki
    value: true
variables:
- group: DefraGitHub
- name: GitHubPipelineServiceConnection
  value: Defra
- name: WindowsHostedAgentPool
  value: windows-latest
- name: UbuntuHostedAgentPool
  value: ubuntu-latest
- name: AllPipelinesJsonArtifactName
  value: AllPipelinesJson
- name: RenamePrefix
  value: ZZZ-Archive-
resources:
  repositories:
  - repository: epr-app-config-settings
    name: RWD-CPR-EPR4P-ADO/epr-app-config-settings
    type: git
  - repository: github-epr-app-config-settings
    name: defra/epr-app-config-settings
    type: github
    endpoint: GitHubMigration
  - repository: backend-account-microservice
    name: RWD-CPR-EPR4P-ADO/backend-account-microservice
    type: git
  - repository: github-epr-backend-account-microservice
    name: defra/epr-backend-account-microservice
    type: github
    endpoint: GitHubMigration
  - repository: epr_common
    name: RWD-CPR-EPR4P-ADO/epr_common
    type: git
  - repository: github-epr-common
    name: defra/epr-common
    type: github
    endpoint: GitHubMigration
  - repository: epr-common-data-api
    name: RWD-CPR-EPR4P-ADO/epr-common-data-api
    type: git
  - repository: github-epr-common-data-api
    name: defra/epr-common-data-api
    type: github
    endpoint: GitHubMigration
  - repository: epr-data
    name: RWD-CPR-EPR4P-ADO/epr-data
    type: git
  - repository: github-epr-data
    name: defra/epr-data
    type: github
    endpoint: GitHubMigration
  - repository: epr-event-dispatcher-function-app
    name: RWD-CPR-EPR4P-ADO/epr-event-dispatcher-function-app
    type: git
  - repository: github-epr-event-dispatcher-function-app
    name: defra/epr-event-dispatcher-function-app
    type: github
    endpoint: GitHubMigration
  - repository: facade-account-microservice
    name: RWD-CPR-EPR4P-ADO/facade-account-microservice
    type: git
  - repository: github-epr-facade-account-microservice
    name: defra/epr-facade-account-microservice
    type: github
    endpoint: GitHubMigration
  - repository: frontend-accountcreation-microservice
    name: RWD-CPR-EPR4P-ADO/frontend-accountcreation-microservice
    type: git
  - repository: github-epr-frontend-accountcreation-microservice
    name: defra/epr-frontend-accountcreation-microservice
    type: github
    endpoint: GitHubMigration
  - repository: frontend-accountmanagement-microservice
    name: RWD-CPR-EPR4P-ADO/frontend-accountmanagement-microservice
    type: git
  - repository: github-epr-frontend-accountmanagement-microservice
    name: defra/epr-frontend-accountmanagement-microservice
    type: github
    endpoint: GitHubMigration
  - repository: epr-logging-api
    name: RWD-CPR-EPR4P-ADO/epr-logging-api
    type: git
  - repository: github-epr-logging-api
    name: defra/epr-logging-api
    type: github
    endpoint: GitHubMigration
  - repository: epr-migration-automation
    name: RWD-CPR-EPR4P-ADO/epr-migration-automation
    type: git
  - repository: github-epr-migration-automation
    name: defra/epr-migration-automation
    type: github
    endpoint: GitHubMigration
  - repository: epr-migration-test1
    name: RWD-CPR-EPR4P-ADO/epr-migration-test1
    type: git
  - repository: github-epr-migration-test1
    name: defra/epr-migration-test1
    type: github
    endpoint: GitHubMigration
  - repository: epr-migration-test2
    name: RWD-CPR-EPR4P-ADO/epr-migration-test2
    type: git
  - repository: github-epr-migration-test2
    name: defra/epr-migration-test2
    type: github
    endpoint: GitHubMigration
  - repository: epr-obligationchecker-frontend
    name: RWD-CPR-EPR4P-ADO/epr-obligationchecker-frontend
    type: git
  - repository: github-epr-obligationchecker-frontend
    name: defra/epr-obligationchecker-frontend
    type: github
    endpoint: GitHubMigration
  - repository: epr_packaging_frontend
    name: RWD-CPR-EPR4P-ADO/epr_packaging_frontend
    type: git
  - repository: github-epr-packaging-frontend
    name: defra/epr-packaging-frontend
    type: github
    endpoint: GitHubMigration
  - repository: epr_pom_api_submission_status
    name: RWD-CPR-EPR4P-ADO/epr_pom_api_submission_status
    type: git
  - repository: github-epr-pom-api-submission-status
    name: defra/epr-pom-api-submission-status
    type: github
    endpoint: GitHubMigration
  - repository: epr_pom_api_web
    name: RWD-CPR-EPR4P-ADO/epr_pom_api_web
    type: git
  - repository: github-epr-pom-api-web
    name: defra/epr-pom-api-web
    type: github
    endpoint: GitHubMigration
  - repository: epr_pom_func_producer_validation
    name: RWD-CPR-EPR4P-ADO/epr_pom_func_producer_validation
    type: git
  - repository: github-epr-pom-func-producer-validation
    name: defra/epr-pom-func-producer-validation
    type: github
    endpoint: GitHubMigration
  - repository: epr_pom_func_submission_check_splitter
    name: RWD-CPR-EPR4P-ADO/epr_pom_func_submission_check_splitter
    type: git
  - repository: github-epr-pom-func-submission-check-splitter
    name: defra/epr-pom-func-submission-check-splitter
    type: github
    endpoint: GitHubMigration
  - repository: epr-registration-validation-function-app
    name: RWD-CPR-EPR4P-ADO/epr-registration-validation-function-app
    type: git
  - repository: github-epr-registration-validation-function-app
    name: defra/epr-registration-validation-function-app
    type: github
    endpoint: GitHubMigration
  - repository: epr-regulator-enrolment-frontend
    name: RWD-CPR-EPR4P-ADO/epr-regulator-enrolment-frontend
    type: git
  - repository: github-epr-regulator-enrolment-frontend
    name: defra/epr-regulator-enrolment-frontend
    type: github
    endpoint: GitHubMigration
  - repository: epr_regulator_service
    name: RWD-CPR-EPR4P-ADO/epr_regulator_service
    type: git
  - repository: github-epr-regulator-service
    name: defra/epr-regulator-service
    type: github
    endpoint: GitHubMigration
  - repository: epr_regulator_service_facade
    name: RWD-CPR-EPR4P-ADO/epr_regulator_service_facade
    type: git
  - repository: github-epr-regulator-service-facade
    name: defra/epr-regulator-service-facade
    type: github
    endpoint: GitHubMigration
  - repository: epr-rpd-performance-tests
    name: RWD-CPR-EPR4P-ADO/epr-rpd-performance-tests
    type: git
  - repository: github-epr-rpd-performance-tests
    name: defra/epr-rpd-performance-tests
    type: github
    endpoint: GitHubMigration
  - repository: epr_ui_wdio
    name: RWD-CPR-EPR4P-ADO/epr_ui_wdio
    type: git
  - repository: github-epr-ui-wdio
    name: defra/epr-ui-wdio
    type: github
    endpoint: GitHubMigration
  - repository: epr-webapps-code-deploy-pipelines
    name: RWD-CPR-EPR4P-ADO/epr-webapps-code-deploy-pipelines
    type: git
  - repository: github-epr-webapps-code-deploy-pipelines
    name: defra/epr-webapps-code-deploy-pipelines
    type: github
    endpoint: GitHubMigration
  - repository: epr-webapps-code-deploy-templates
    name: RWD-CPR-EPR4P-ADO/epr-webapps-code-deploy-templates
    type: git
  - repository: github-epr-webapps-code-deploy-templates
    name: defra/epr-webapps-code-deploy-templates
    type: github
    endpoint: GitHubMigration
extends:
  template: templates/pipeline-migration.yaml
  parameters:
    AdoAccessToken: $(System.AccessToken)
    AdoOrganizationUrl: $(System.CollectionUri)
    AdoTeamProject: $(System.TeamProject)
    AllPipelinesJsonArtifactName: ${{ variables.AllPipelinesJsonArtifactName }}
    GitHubAccessToken: $(GitHubAccessToken)
    GitHubOrganizationName: $(GitHubOrganizationName)
    GitHubPipelineServiceConnection: $(GitHubPipelineServiceConnection)
    GitHubRepoSettings: ${{ parameters.GitHubRepoSettings }}
    GitHubServiceConnection: $(GitHubServiceConnection)
    GitLeaksFailureAsWarning: ${{ parameters.GitLeaksFailureAsWarning }}
    MigrationData: ${{ parameters.MigrationData }}
    RenamePrefix: ${{ variables.RenamePrefix }}
    UbuntuHostedAgentPool: ${{ variables.UbuntuHostedAgentPool }}
    WindowsHostedAgentPool: ${{ variables.WindowsHostedAgentPool }}

