trigger: none

parameters:
- name: SourceRepo
  displayName: Repo to rename
  type: string
  default: 'ZZZ-Archive-epr-migration-test2'

- name: NewName
  displayName: New name
  type: string
  default: 'epr-migration-test2'

- name: WhatIf
  displayName: WhatIf
  type: boolean
  default: false

variables:
- name: HostedAgentPool 
  value: ubuntu-latest
- name: AdoOrganizationUrl
  value: '$(System.CollectionUri)'
- name: AdoTeamProject
  value: '$(System.TeamProject)'
- name: AdoAccessToken
  value: '$(System.AccessToken)'

resources: 
  repositories:
  # ZZZ-Archive-epr-migration-test2
  - repository: ZZZ-Archive-epr-migration-test2
    name: RWD-CPR-EPR4P-ADO/ZZZ-Archive-epr-migration-test2
    type: git

stages:
- stage: ResetPullRequestsStage  
  displayName: Rename repo
  dependsOn: ''
  jobs: 
  - template: templates/job-renamerepo.yaml
    parameters:
      JobName: RenameRepoJob
      DependsOn: ''
      HostedAgentPool: ${{ variables.HostedAgentPool }}
      AdoOrganizationUrl: ${{ variables.AdoOrganizationUrl }}
      AdoTeamProject: ${{ variables.AdoTeamProject }}
      AdoAccessToken: ${{ variables.AdoAccessToken }}
      OldRepoName: '${{ parameters.SourceRepo }}'
      NewRepoName: '${{ parameters.NewName }}'
      WhatIf: ${{ parameters.WhatIf }}
