trigger: none

parameters:
- name: TargetPlatforms
  type: object
  default: 
  - ubuntu
  - windows

resources: 
  repositories:
  - repository: gitleaks
    name: gitleaks/gitleaks
    type: github
    endpoint: defra

stages:
- stage: BuildGitLeaksStage
  displayName: Build gitleaks
  dependsOn: ''
  jobs: 
  - ${{ each targetOS in parameters.TargetPlatforms }}:
    - template: templates/job-buildgitleaks.yaml
      parameters:
        JobName: Build${{ targetOS}}GitLeaksJob
        DependsOn: ''
        HostedAgentPool: ${{ targetOS }}-latest
        ArtifactName: GitLeaks-${{ targetOS }}
